application:
  subdomain: roon-server
  background_task: true
  multi_instance: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://roon-server.lazycat.community.app.roon-server.lzcapp:9330/display
  depends_on:
    - roon-server

services:
  roon-server:
    image: docker.1ms.run/czyt/roon-server:v2.65.1653
    user: root
    binds:
      - /lzcapp/run/mnt/home/music:/music
      - /lzcapp/var/data:/var/roon
      - /lzcapp/var/backup:/backup
    net_admin: true
    network_mode: host

ext_config:
  enable_document_access: true
  enable_media_access: true
