lzc-sdk-version: "0.1"
name: RoonServer
package: lazycat.community.app.roon-server
version: 2.47.1510
description: 关于音乐的一切--浏览、发现、收集和聆听--在Roon的帮助下，参与度提高了10倍。
homepage: https://roon.app/zh-Hans/
author: roon
application:
  subdomain: roon-server
  background_task: trues
  multi_instance: true
  public_path:
    - /
  routes:
    - /=file:///lzcapp/pkg/content
  depends_on:
    - roon-server


services:
  roon-server:
    image: docker.1ms.run/czyt/roon-server:v2.47.1510
    user: root
    binds:
      - /lzcapp/run/mnt/home/music:/music
      - /lzcapp/var/data:/data
      - /lzcapp/var/backup:/backup
    net_admin: true
    network_mode: host
ext_config:
  enable_document_access: true
  enable_media_access: true
